# Generated by Django 4.2 on 2024-07-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageInfo',
        ),
    ]
