# Generated by Django 4.2 on 2024-07-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_images_rename_image_imageinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ImageIn',
        ),
    ]
