# Generated by Django 4.2 on 2024-07-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_images_imagein'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageIn',
            new_name='Image',
        ),
    ]
