# Generated by Django 4.2 on 2024-07-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_image_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Surves',
        ),
    ]
