# Generated by Django 4.2 on 2024-07-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_images_surves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Surves',
        ),
    ]
